Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      MemorySize: 1024
      Handler: helloworld.App
      CodeUri: /Users/mohammadvahidalizadehdizaj/IdeaProjects/aws_hello_world/HelloWorldFunction
      Runtime: java11